name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: .

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "bun"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Node Dependencies
        run: bun ci
      - name: Build storybook
        run: bun run build-storybook
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
